global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'development'
    project: 'sssp'

scrape_configs:
  # SSSP API Metrics
  - job_name: 'sssp-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8080']
        labels:
          service: 'api'
          component: 'dotnet'

  # Prometheus Mointor
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
          component: 'monitoring'